# Generated by Django 4.0.1 on 2022-03-29 03:39

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('breed', models.CharField(default='N', max_length=25)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('N', 'Genderless')], default='N', max_length=1, null=True)),
                ('ability', models.CharField(blank=True, max_length=15, null=True)),
                ('nature', models.CharField(blank=True, choices=[('1', 'Hardy'), ('2', 'Lonely'), ('3', 'Brave'), ('4', 'Adament'), ('5', 'Naughty'), ('6', 'Bold'), ('7', 'Docile'), ('8', 'Relaxed'), ('9', 'Impish'), ('10', 'Lax'), ('11', 'Timid'), ('12', 'Hasty'), ('13', 'Serious'), ('14', 'Jolly'), ('15', 'Naive'), ('16', 'Modest'), ('17', 'Mild'), ('18', 'Quiet'), ('19', 'Bashful'), ('20', 'Rash'), ('21', 'Calm'), ('22', 'Gentle'), ('23', 'Sassy'), ('24', 'Careful'), ('25', 'Quirky'), ('26', '-')], default='26', max_length=7)),
                ('item', models.CharField(blank=True, max_length=15, null=True)),
                ('move1', models.CharField(blank=True, max_length=20, null=True)),
                ('move2', models.CharField(blank=True, max_length=20, null=True)),
                ('move3', models.CharField(blank=True, max_length=20, null=True)),
                ('move4', models.CharField(blank=True, max_length=20, null=True)),
                ('level', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('hp', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('attack', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('defense', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('spec_atk', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('spec_def', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('speed', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('charactaristic', models.TextField(blank=True, null=True)),
                ('met', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('teamname', models.CharField(max_length=15)),
                ('game', models.CharField(max_length=15)),
                ('region', models.CharField(max_length=15)),
                ('id_no', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999)])),
                ('pokedex_seen', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(901)])),
                ('pokedex_caught', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(901)])),
                ('money', models.PositiveIntegerField(blank=True, null=True)),
                ('date_started', models.DateField(blank=True, null=True)),
                ('time', models.DurationField(blank=True, null=True)),
                ('badges', models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(16)])),
                ('hall_of_fame', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('box', models.ManyToManyField(blank=True, default=None, related_name='+', to='pokemon.Pokemon')),
                ('main', models.ManyToManyField(blank=True, default=None, related_name='+', to='pokemon.Pokemon')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='pokemon',
            name='team',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='pokemon.team'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
