# Generated by Django 4.0.1 on 2022-03-29 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='time',
        ),
        migrations.AddField(
            model_name='team',
            name='times',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
