# Generated by Django 4.0.1 on 2022-03-29 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0002_remove_team_time_team_times'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='times',
            new_name='time',
        ),
    ]
