# Generated by Django 4.0.1 on 2022-03-29 05:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0003_rename_times_team_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='time',
        ),
        migrations.AddField(
            model_name='team',
            name='time_hours',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='time_minutes',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(59)]),
        ),
    ]
