# Generated by Django 4.0.1 on 2022-04-03 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0004_remove_team_time_team_time_hours_team_time_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='type1',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='type2',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='nature',
            field=models.CharField(blank=True, default='26', max_length=7),
        ),
    ]
