# Generated by Django 4.0.1 on 2022-04-11 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0005_pokemon_type1_pokemon_type2_alter_pokemon_nature'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='form',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='nature',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
