# Generated by Django 4.0.1 on 2022-04-11 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0006_pokemon_form_alter_pokemon_nature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='nature',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
