# Generated by Django 4.0.1 on 2022-04-12 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0007_alter_pokemon_nature'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='is_shiny',
            field=models.BooleanField(default=False),
        ),
    ]
