# Generated by Django 4.0.1 on 2022-04-12 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0008_pokemon_is_shiny'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='type1',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='type2',
        ),
    ]
