# Generated by Django 4.0.1 on 2022-04-14 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0011_pokemon_date_created_team_date_created_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pokemon',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['-date_created']},
        ),
        migrations.AddField(
            model_name='team',
            name='formal_defeats',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='total_defeats',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='victories',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
